language: python
env:
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=flake8
  - TOXENV=sphinx
  - TOXENV=readme
install:
script:
  - make test
